import { Film, Genre, Language, Submission } from '@/types';

export const mockLanguages: Language[] = [
  { id: 'l1', name: 'Hindi', code: 'hi', native_name: 'हिन्दी', created_at: new Date().toISOString() },
  { id: 'l2', name: 'Gujarati', code: 'gu', native_name: 'ગુજરાતી', created_at: new Date().toISOString() },
  { id: 'l3', name: 'Tamil', code: 'ta', native_name: 'தமிழ்', created_at: new Date().toISOString() },
  { id: 'l4', name: 'Telugu', code: 'te', native_name: 'తెలుగు', created_at: new Date().toISOString() },
  { id: 'l5', name: 'Malayalam', code: 'ml', native_name: 'മലയാളം', created_at: new Date().toISOString() },
  { id: 'l6', name: 'Kannada', code: 'kn', native_name: 'ಕನ್ನಡ', created_at: new Date().toISOString() },
  { id: 'l7', name: 'Marathi', code: 'mr', native_name: 'मराठी', created_at: new Date().toISOString() },
  { id: 'l8', name: 'Bengali', code: 'bn', native_name: 'বাংলা', created_at: new Date().toISOString() },
  { id: 'l9', name: 'Punjabi', code: 'pa', native_name: 'ਪੰਜਾਬੀ', created_at: new Date().toISOString() },
  { id: 'l10', name: 'English', code: 'en', native_name: 'English', created_at: new Date().toISOString() }
];

export const mockGenres: Genre[] = [
  { id: 'g1', name: 'Drama', slug: 'drama', description: 'Heartfelt emotional stories', icon: 'film', created_at: new Date().toISOString() },
  { id: 'g2', name: 'Comedy', slug: 'comedy', description: 'Lighthearted slice-of-life humor', icon: 'smile', created_at: new Date().toISOString() },
  { id: 'g3', name: 'Thriller', slug: 'thriller', description: 'Edge-of-the-seat suspense', icon: 'zap', created_at: new Date().toISOString() },
  { id: 'g4', name: 'Horror', slug: 'horror', description: 'Psychological chills & supernatural tales', icon: 'ghost', created_at: new Date().toISOString() },
  { id: 'g5', name: 'Romance', slug: 'romance', description: 'Poetic love and relational connections', icon: 'heart', created_at: new Date().toISOString() },
  { id: 'g6', name: 'Documentary', slug: 'documentary', description: 'Real-world Indian social & cultural stories', icon: 'camera', created_at: new Date().toISOString() },
  { id: 'g7', name: 'Sci-Fi', slug: 'sci-fi', description: 'Futuristic Indian cinema concepts', icon: 'cpu', created_at: new Date().toISOString() },
  { id: 'g8', name: 'Animation', slug: 'animation', description: 'Visual stories and 2D/3D animation', icon: 'sparkles', created_at: new Date().toISOString() }
];

export const mockFilms: Film[] = [
  {
    id: 'film-1',
    title: 'The Last Note',
    slug: 'the-last-note',
    description: 'A passionate classical violinist in the mist-laden hills of Chikmagalur struggles to compose his farewell masterpiece while losing his hearing.',
    poster_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration_seconds: 1080,
    release_year: 2024,
    certificate: 'U',
    director: 'Aarav Sharma',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 42300,
    likes_count: 1420,
    rating_average: 4.9,
    rating_count: 142,
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-2',
    title: 'Maya: Illusions of Malnad',
    slug: 'maya-illusions-of-malnad',
    description: 'A folklore researcher visits a sacred grove in Shivamogga and encounters the enigmatic guardian deity of the Western Ghats.',
    poster_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration_seconds: 1320,
    release_year: 2024,
    certificate: 'U',
    director: 'Priya Hegde',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 56100,
    likes_count: 1890,
    rating_average: 4.8,
    rating_count: 189,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[2]]
  },
  {
    id: 'film-3',
    title: 'Kaalchakra - The Wheel',
    slug: 'kaalchakra-the-wheel',
    description: 'An antique clockmaker in Varanasi uncovers a rhythmic time-loop apparatus that rewinds the holy city by seven minutes every sunset.',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration_seconds: 900,
    release_year: 2024,
    certificate: 'U',
    director: 'Vikramaditya Roy',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 78900,
    likes_count: 2310,
    rating_average: 4.7,
    rating_count: 231,
    created_at: new Date(Date.now() - 13 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    languages: [mockLanguages[0]],
    genres: [mockGenres[2]]
  },
  {
    id: 'film-4',
    title: 'Bengaluru 6 AM',
    slug: 'bengaluru-6-am',
    description: 'Two strangers meet at an iconic filter coffee darshini in Basavanagudi as the sunrise mist covers the city streets.',
    poster_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration_seconds: 720,
    release_year: 2024,
    certificate: 'U',
    director: 'Karthik Rao',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 31200,
    likes_count: 980,
    rating_average: 4.6,
    rating_count: 98,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-5',
    title: 'Vanishing Echoes',
    slug: 'vanishing-echoes',
    description: 'An evocative documentary exploring the ancient ritual songs of the Theyyam performers through nocturnal backwaters.',
    poster_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    duration_seconds: 1440,
    release_year: 2024,
    certificate: 'U',
    director: 'Meera Nambiar',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 48900,
    likes_count: 1650,
    rating_average: 4.9,
    rating_count: 165,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    languages: [mockLanguages[4]],
    genres: [mockGenres[5]]
  },
  {
    id: 'film-6',
    title: 'Karnad\'s Solitude',
    slug: 'karnad-s-solitude',
    description: 'A tribute to classical Kannada theatre exploring a playwright facing the empty stage before a historic premiere.',
    poster_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration_seconds: 1560,
    release_year: 2024,
    certificate: 'U',
    director: 'Suhas Kulkarni',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 65400,
    likes_count: 2100,
    rating_average: 4.8,
    rating_count: 210,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[5]]
  },
  {
    id: 'film-7',
    title: 'Nila: Blue Horizon',
    slug: 'nila-blue-horizon',
    description: 'A deaf painter and an acoustic recordist capture the changing sounds of Chennai shores before the monsoons arrive.',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration_seconds: 960,
    release_year: 2024,
    certificate: 'U',
    director: 'Arvind Swamy',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 89300,
    likes_count: 3420,
    rating_average: 4.8,
    rating_count: 342,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    languages: [mockLanguages[2]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-8',
    title: 'The Clay Potter of Kutch',
    slug: 'the-clay-potter-of-kutch',
    description: 'The meditative rhythm of salt plains and terracotta wheels in the arid beauty of Gujarat white desert.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration_seconds: 1140,
    release_year: 2024,
    certificate: 'U',
    director: 'Bhavna Patel',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 38400,
    likes_count: 1120,
    rating_average: 4.7,
    rating_count: 112,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    languages: [mockLanguages[1]],
    genres: [mockGenres[5]]
  },
  {
    id: 'film-9',
    title: 'Midnight Express',
    slug: 'midnight-express',
    description: 'A single train compartment, six unacquainted passengers, and an unaddressed telegram that changes everything.',
    poster_url: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration_seconds: 840,
    release_year: 2024,
    certificate: 'U',
    director: 'Aarav Sharma',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 71200,
    likes_count: 2780,
    rating_average: 4.9,
    rating_count: 278,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    languages: [mockLanguages[0]],
    genres: [mockGenres[2]]
  },
  {
    id: 'film-10',
    title: 'Chai & Stories',
    slug: 'chai-stories',
    description: 'Over steaming clay cups of ginger tea, an artisan and an aspiring animator connect across generational gaps.',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration_seconds: 660,
    release_year: 2024,
    certificate: 'U',
    director: 'Ananya Sen',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 29800,
    likes_count: 1450,
    rating_average: 4.8,
    rating_count: 145,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-11',
    title: 'Kaveri Calling',
    slug: 'kaveri-calling',
    description: 'A tribute to Karnataka sacred river valley through the eyes of its village elders.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    duration_seconds: 1080,
    release_year: 2024,
    certificate: 'U',
    director: 'Chetan Gowda',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 45600,
    likes_count: 1840,
    rating_average: 4.8,
    rating_count: 184,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-12',
    title: 'The Silent Ghat',
    slug: 'the-silent-ghat',
    description: 'A mist-veiled morning on the Hooghly river where an old ferryman reveals a decades-old town mystery.',
    poster_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration_seconds: 1020,
    release_year: 2024,
    certificate: 'U',
    director: 'Sourav Mukherjee',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 52100,
    likes_count: 1980,
    rating_average: 4.7,
    rating_count: 198,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    languages: [mockLanguages[7]],
    genres: [mockGenres[2]]
  },
  {
    id: 'film-13',
    title: 'The Amber Loom',
    slug: 'the-amber-loom',
    description: 'A traditional Benarasi silk weaver weaves his ancestral pattern for one final customer.',
    poster_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration_seconds: 900,
    release_year: 2024,
    certificate: 'U',
    director: 'Manoj Verma',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 34100,
    likes_count: 1220,
    rating_average: 4.6,
    rating_count: 122,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    languages: [mockLanguages[0]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-14',
    title: 'Godavari Rhythms',
    slug: 'godavari-rhythms',
    description: 'A celebration of Godavari delta folk musicians seeking to preserve river ballad poetry.',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration_seconds: 1260,
    release_year: 2024,
    certificate: 'U',
    director: 'Venkatesh Rao',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 84200,
    likes_count: 2890,
    rating_average: 4.8,
    rating_count: 289,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    languages: [mockLanguages[3]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-15',
    title: 'Whispers of Sahyadri',
    slug: 'whispers-of-sahyadri',
    description: 'Trekkers traversing the historic forts of Shivaji Maharaj uncover an undisturbed cavern archive.',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration_seconds: 1200,
    release_year: 2024,
    certificate: 'U',
    director: 'Tanvi Joshi',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 46200,
    likes_count: 1760,
    rating_average: 4.7,
    rating_count: 176,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    languages: [mockLanguages[6]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-16',
    title: 'The Basavanagudi Postman',
    slug: 'the-basavanagudi-postman',
    description: 'A heartwarming journey of a veteran postman delivering handwritten letters across heritage South Bangalore.',
    poster_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration_seconds: 780,
    release_year: 2024,
    certificate: 'U',
    director: 'Karthik Rao',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 39800,
    likes_count: 1540,
    rating_average: 4.8,
    rating_count: 154,
    created_at: new Date(Date.now() - 13 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-17',
    title: 'Rain over Fort Kochi',
    slug: 'rain-over-fort-kochi',
    description: 'Chinese fishing nets, sudden monsoon showers, and two travelers stranded under an antique colonial portico.',
    poster_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration_seconds: 840,
    release_year: 2024,
    certificate: 'U',
    director: 'Meera Nambiar',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 68100,
    likes_count: 2450,
    rating_average: 4.9,
    rating_count: 245,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    languages: [mockLanguages[4]],
    genres: [mockGenres[4]]
  },
  {
    id: 'film-18',
    title: 'Kathakali: Face of gods',
    slug: 'kathakali-face-of-gods',
    description: 'Intimate visual poetry revealing the six hours of sacred facial makeup transformation of a master Kathakali artist.',
    poster_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration_seconds: 1500,
    release_year: 2024,
    certificate: 'U',
    director: 'Suresh Menon',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 92400,
    likes_count: 3100,
    rating_average: 4.9,
    rating_count: 310,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    languages: [mockLanguages[4]],
    genres: [mockGenres[5]]
  },
  {
    id: 'film-19',
    title: 'The Hyderabad Cafe',
    slug: 'the-hyderabad-cafe',
    description: 'A hilarious yet poignant negotiation between three cousins inside an old Irani Chai cafe in Charminar.',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration_seconds: 960,
    release_year: 2024,
    certificate: 'U',
    director: 'Faizan Ahmed',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 47200,
    likes_count: 1890,
    rating_average: 4.7,
    rating_count: 189,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    languages: [mockLanguages[3]],
    genres: [mockGenres[0]]
  },
  {
    id: 'film-20',
    title: 'Shadows of Ahmedabad',
    slug: 'shadows-of-ahmedabad',
    description: 'The winding Pols of heritage Ahmedabad, carved wooden Havelis, and an untold story from the 1960s.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    banner_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1920&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration_seconds: 1080,
    release_year: 2024,
    certificate: 'U',
    director: 'Bhavna Patel',
    producer: 'Independent',
    cast_members: [],
    production_house: 'Independent',
    status: 'approved',
    visibility: 'public',
    views_count: 41900,
    likes_count: 1670,
    rating_average: 4.8,
    rating_count: 167,
    created_at: new Date(Date.now() - 0 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    languages: [mockLanguages[1]],
    genres: [mockGenres[0]]
  }
];

export const mockSubmissions: Submission[] = [];
