import { Film, Genre, Language, Submission } from '@/types';

export const mockLanguages: Language[] = [
  { id: 'l1', name: 'Hindi', code: 'hi', native_name: 'हिन्दी', created_at: new Date().toISOString() },
  { id: 'l2', name: 'Gujarati', code: 'gu', native_name: 'ગુજરાતી', created_at: new Date().toISOString() },
  { id: 'l3', name: 'Tamil', code: 'ta', native_name: 'தமிழ்', created_at: new Date().toISOString() },
  { id: 'l4', name: 'Telugu', code: 'te', native_name: 'తెలుగు', created_at: new Date().toISOString() },
  { id: 'l5', name: 'Malayalam', code: 'ml', native_name: 'മലയാളം', created_at: new Date().toISOString() },
  { id: 'l6', name: 'Kannada', code: 'kn', native_name: 'ಕನ್ನಡ', created_at: new Date().toISOString() },
  { id: 'l7', name: 'Marathi', code: 'mr', native_name: 'मराठी', created_at: new Date().toISOString() },
  { id: 'l8', name: 'Bengali', code: 'bn', native_name: 'বাংলা', created_at: new Date().toISOString() },
  { id: 'l9', name: 'Punjabi', code: 'pa', native_name: 'ਪੰਜਾਬੀ', created_at: new Date().toISOString() },
  { id: 'l10', name: 'English', code: 'en', native_name: 'English', created_at: new Date().toISOString() }
];

export const mockGenres: Genre[] = [
  { id: 'g1', name: 'Drama', slug: 'drama', description: 'Heartfelt emotional stories', icon: 'film', created_at: new Date().toISOString() },
  { id: 'g2', name: 'Comedy', slug: 'comedy', description: 'Lighthearted slice-of-life humor', icon: 'smile', created_at: new Date().toISOString() },
  { id: 'g3', name: 'Thriller', slug: 'thriller', description: 'Edge-of-the-seat suspense', icon: 'zap', created_at: new Date().toISOString() },
  { id: 'g4', name: 'Horror', slug: 'horror', description: 'Psychological chills & supernatural tales', icon: 'ghost', created_at: new Date().toISOString() },
  { id: 'g5', name: 'Romance', slug: 'romance', description: 'Poetic love and relational connections', icon: 'heart', created_at: new Date().toISOString() },
  { id: 'g6', name: 'Documentary', slug: 'documentary', description: 'Real-world Indian social & cultural stories', icon: 'camera', created_at: new Date().toISOString() },
  { id: 'g7', name: 'Sci-Fi', slug: 'sci-fi', description: 'Futuristic Indian cinema concepts', icon: 'cpu', created_at: new Date().toISOString() },
  { id: 'g8', name: 'Animation', slug: 'animation', description: 'Visual stories and 2D/3D animation', icon: 'sparkles', created_at: new Date().toISOString() }
];

export const mockFilms: Film[] = [
  {
    id: 'f1',
    title: 'Chai & Stories (चाय और किस्से)',
    slug: 'chai-and-stories',
    description: 'A poignant tale set in a bustling Mumbai tea stall where two strangers discover an unexpected connection over evening masala chai. (Demo Content)',
    poster_url: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80',
    banner_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration_seconds: 720,
    release_year: 2024,
    certificate: 'U',
    director: 'Aarav Sharma',
    producer: 'Meera Kapoor',
    cast_members: [{ name: 'Rohan Joshi', role: 'Kabir' }, { name: 'Priya Roy', role: 'Ananya' }],
    production_house: 'Katha Independent Talkies',
    status: 'approved',
    visibility: 'public',
    views_count: 1450,
    likes_count: 320,
    rating_average: 4.80,
    rating_count: 45,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    languages: [mockLanguages[0]],
    genres: [mockGenres[0]]
  },
  {
    id: 'f2',
    title: 'The Last Letter (અંતિમ પત્ર)',
    slug: 'the-last-letter',
    description: 'A nostalgic Gujarati short film exploring an elderly artisan\'s journey through forgotten letters in vintage Ahmedabad. (Demo Content)',
    poster_url: 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=600&q=80',
    banner_url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration_seconds: 950,
    release_year: 2024,
    certificate: 'U',
    director: 'Devang Patel',
    producer: 'Kavita Patel',
    cast_members: [{ name: 'Hasmukh Vora', role: 'Dada Ji' }, { name: 'Kinjal Shah', role: 'Granddaughter' }],
    production_house: 'Sabarmati Cinema',
    status: 'approved',
    visibility: 'public',
    views_count: 980,
    likes_count: 210,
    rating_average: 4.65,
    rating_count: 28,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    languages: [mockLanguages[1]],
    genres: [mockGenres[0]]
  },
  {
    id: 'f3',
    title: 'Midnight Express (இரவு பயணம்)',
    slug: 'midnight-express',
    description: 'A gripping Tamil psychological thriller centered around a late-night commuter in Chennai who notices a mysterious suitcase. (Demo Content)',
    poster_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration_seconds: 840,
    release_year: 2023,
    certificate: 'UA 13+',
    director: 'Karthik Raja',
    producer: 'Venkatesh Iyer',
    cast_members: [{ name: 'Surya Kumar', role: 'Vikram' }, { name: 'Divya Nambiar', role: 'Stranger' }],
    production_house: 'Marina Wave Pictures',
    status: 'approved',
    visibility: 'public',
    views_count: 2300,
    likes_count: 540,
    rating_average: 4.90,
    rating_count: 62,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    languages: [mockLanguages[2]],
    genres: [mockGenres[2]]
  },
  {
    id: 'f4',
    title: 'Shadows of Mysore (ಮೈಸೂರು ನೆರಳುಗಳು)',
    slug: 'shadows-of-mysore',
    description: 'An evocative Kannada mystery exploring historical secrets hidden inside centuries-old royal silk looms. (Demo Content)',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    banner_url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    duration_seconds: 1100,
    release_year: 2024,
    certificate: 'U',
    director: 'Ramesh Gowda',
    producer: 'Sujata Rao',
    cast_members: [{ name: 'Chetan Kumar', role: 'Rajesh' }, { name: 'Shreya Hegde', role: 'Kavya' }],
    production_house: 'Kaveri Talkies',
    status: 'approved',
    visibility: 'public',
    views_count: 1120,
    likes_count: 195,
    rating_average: 4.50,
    rating_count: 19,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    languages: [mockLanguages[5]],
    genres: [mockGenres[2]]
  },
  {
    id: 'f5',
    title: 'Monsoon Melodies (వర్షం స్వరాలు)',
    slug: 'monsoon-melodies',
    description: 'A heartwarming Telugu romantic drama about two musicians creating a song during a heavy Hyderabad rainstorm. (Demo Content)',
    poster_url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80',
    banner_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    trailer_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    duration_seconds: 660,
    release_year: 2024,
    certificate: 'U',
    director: 'Teja Varma',
    producer: 'Anitha Reddy',
    cast_members: [{ name: 'Varun Tej', role: 'Sid' }, { name: 'Keerthy S.', role: 'Riya' }],
    production_house: 'Deccan Beats Studio',
    status: 'approved',
    visibility: 'public',
    views_count: 1890,
    likes_count: 430,
    rating_average: 4.75,
    rating_count: 51,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    languages: [mockLanguages[3]],
    genres: [mockGenres[4]]
  }
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    filmmaker_id: 'fm-1',
    title: 'Echoes of the Thar (थार की गूंज)',
    description: 'A documentary exploring folk musicians in Rajasthan who preserve ancient vocal traditions across remote desert dunes. (Demo Submission)',
    poster_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration_seconds: 1400,
    release_year: 2024,
    director: 'Kabir Rathore',
    producer: 'Sunita Rathore',
    status: 'submitted',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'sub-2',
    filmmaker_id: 'fm-2',
    title: 'Kolkata Tramway 88 (কলকাতা ট্রাম ৮৮)',
    description: 'A romantic short story capturing a nostalgic ride aboard Kolkata\'s historic electric streetcar. (Demo Submission)',
    poster_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    duration_seconds: 880,
    release_year: 2024,
    director: 'Subhashish Ghosh',
    producer: 'Moumi Banerjee',
    status: 'submitted',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString()
  }
];
